export const PERMISSION_REGISTRY = {
  'orders.view': ['orders', 'View orders'],
  'orders.accept': ['orders', 'Accept pending orders'],
  'orders.reject': ['orders', 'Reject pending orders'],
  'orders.prepare': ['orders', 'Move accepted orders into preparation'],
  'orders.mark_ready': ['orders', 'Mark prepared orders ready'],
  'orders.handover': ['orders', 'Hand ready orders to delivery'],
  'orders.cancel': ['orders', 'Cancel an order'],
  'orders.cancel_request.resolve': [
    'orders',
    'Approve or deny cancellation requests',
  ],
  'orders.deliver': ['orders', 'Mark a dispatched order delivered'],
  'orders.fail': ['orders', 'Record a failed delivery'],
  'orders.retry': ['orders', 'Retry a failed delivery'],
  'orders.cancel_after_dispatch': ['orders', 'Cancel an order after dispatch'],
  'orders.shortage.resolve': ['orders', 'Resolve preparation shortages'],
  'orders.assign_agent': ['orders', 'Assign a delivery agent'],
  'catalog.categories': ['catalog', 'Manage categories'],
  'catalog.brands': ['catalog', 'Manage brands'],
  'catalog.products': ['catalog', 'Manage products and banners'],
  'prices.change': ['catalog', 'Change sale prices'],
  'prices.publish_linked': ['catalog', 'Publish linked SKU prices'],
  'sell_below_cost.approve': ['catalog', 'Approve a sale below protected cost'],
  'cost.view': ['purchasing', 'View product cost'],
  'suppliers.view': ['purchasing', 'View suppliers'],
  'suppliers.manage': ['purchasing', 'Manage suppliers'],
  'purchases.create': ['purchasing', 'Create purchase invoices'],
  'purchases.correct': ['purchasing', 'Correct purchase invoices'],
  'purchases.override_rate': ['purchasing', 'Override purchase exchange rates'],
  'supplier_openings.record': [
    'purchasing',
    'Record supplier opening balances',
  ],
  'supplier_payments.record': [
    'purchasing',
    'Record and allocate supplier payments',
  ],
  'supplier_payments.reverse': ['purchasing', 'Reverse supplier payments'],
  'supplier_credits.allocate': ['purchasing', 'Allocate supplier credits'],
  'supplier_returns.create': [
    'purchasing',
    'Return purchased stock to suppliers',
  ],
  'payments.record': ['payments', 'Record payments'],
  'payments.reverse': ['payments', 'Reverse payments'],
  'inventory.count': ['inventory', 'Count inventory'],
  'inventory.pick': ['inventory', 'Pick reserved inventory'],
  'inventory.transfer': ['inventory', 'Transfer inventory'],
  'inventory.adjust': ['inventory', 'Adjust inventory'],
  'inventory.view': ['inventory', 'View warehouses, lots and movements'],
  'inventory.manage': ['inventory', 'Manage warehouses and opening stock'],
  'inventory.write_down': ['inventory', 'Write down damaged or expired stock'],
  'retrieval.view': ['inventory', 'View retrieval documents'],
  'retrieval.open': ['inventory', 'Open failed-delivery retrievals'],
  'retrieval.receive': ['inventory', 'Receive goods from delivery custody'],
  'returns.inspect': ['returns', 'Inspect returns'],
  'returns.approve': ['returns', 'Approve returns'],
  'returns.refund': ['returns', 'Refund returns'],
  'reviews.moderate': ['reviews', 'Moderate product reviews'],
  'loyalty.adjust': ['loyalty', 'Adjust loyalty balances'],
  'deliveries.manage': ['deliveries', 'List and manage deliveries'],
  'drivers.manage': ['deliveries', 'Manage external delivery drivers'],
  'users.manage': ['access', 'Manage staff and work phones'],
  'roles.manage': ['access', 'Manage permission presets'],
  'audit.view': ['access', 'View audit logs'],
  'fx_rates.view': ['finance', 'View currencies and exchange rates'],
  'fx_rates.update': ['finance', 'Update exchange rates'],
  'ledger.view': ['finance', 'View ledger and trial balance'],
  'ledger.reverse': ['finance', 'Reverse posted ledger entries'],
  'cash_accounts.view': ['finance', 'View cash and bank accounts'],
  'cash_accounts.manage': ['finance', 'Manage cash and bank accounts'],
  'period.reopen': ['accounting', 'Reopen closed accounting periods'],
  'backdate.approve': [
    'controls',
    'Approve documents outside the back-dating window',
  ],
  'settings.manage': ['settings', 'Manage store settings'],
  'reports.view': ['reports', 'View reports'],
  'period.close': ['accounting', 'Close accounting periods'],
} as const;

export type PermissionKey = keyof typeof PERMISSION_REGISTRY;

export const PERMISSION_KEYS = Object.freeze(
  Object.keys(PERMISSION_REGISTRY) as PermissionKey[],
);

export function isPermissionKey(value: string): value is PermissionKey {
  return Object.prototype.hasOwnProperty.call(PERMISSION_REGISTRY, value);
}

/**
 * Read access required for an action to be usable from end to end. Keep this
 * map declarative: seeded presets are checked against it in CI, while route
 * policies remain the enforcement boundary for each individual request.
 */
export const PERMISSION_DEPENDENCIES: Partial<
  Record<PermissionKey, readonly PermissionKey[]>
> = {
  'orders.accept': ['orders.view'],
  'orders.reject': ['orders.view'],
  'orders.prepare': ['orders.view'],
  'orders.mark_ready': ['orders.view'],
  'orders.handover': ['orders.view'],
  'orders.cancel': ['orders.view'],
  'orders.cancel_request.resolve': ['orders.view'],
  'orders.deliver': ['orders.view'],
  'orders.fail': ['orders.view'],
  'orders.retry': ['orders.view'],
  'orders.cancel_after_dispatch': ['orders.view'],
  'orders.shortage.resolve': ['orders.view'],
  'orders.assign_agent': ['orders.view'],
  'prices.change': ['catalog.products'],
  'prices.publish_linked': ['catalog.products', 'fx_rates.view'],
  'sell_below_cost.approve': ['catalog.products', 'cost.view'],
  'suppliers.manage': ['suppliers.view'],
  'purchases.create': ['suppliers.view', 'inventory.view', 'cost.view'],
  'purchases.correct': ['suppliers.view', 'inventory.view', 'cost.view'],
  'purchases.override_rate': ['fx_rates.view'],
  'supplier_openings.record': ['suppliers.view'],
  'supplier_payments.record': [
    'suppliers.view',
    'cash_accounts.view',
    'fx_rates.view',
  ],
  'supplier_payments.reverse': ['suppliers.view', 'cash_accounts.view'],
  'supplier_credits.allocate': ['suppliers.view'],
  'supplier_returns.create': ['suppliers.view', 'inventory.view', 'cost.view'],
  'inventory.count': ['inventory.view'],
  'inventory.pick': ['inventory.view'],
  'inventory.transfer': ['inventory.view'],
  'inventory.adjust': ['inventory.view'],
  'inventory.manage': ['inventory.view'],
  'inventory.write_down': ['inventory.view', 'cost.view'],
  'retrieval.open': ['retrieval.view'],
  'retrieval.receive': ['retrieval.view'],
  'drivers.manage': ['deliveries.manage'],
  'fx_rates.update': ['fx_rates.view'],
  'ledger.reverse': ['ledger.view'],
  'cash_accounts.manage': ['cash_accounts.view'],
  'period.reopen': ['ledger.view'],
  'period.close': ['ledger.view'],
};

export const SEEDED_PRESET_GRANTS = {
  super_admin: PERMISSION_KEYS,
  operations: [
    'orders.view',
    'orders.accept',
    'orders.reject',
    'orders.prepare',
    'orders.mark_ready',
    'orders.handover',
    'orders.cancel',
    'orders.cancel_request.resolve',
    'orders.deliver',
    'orders.fail',
    'orders.retry',
    'orders.cancel_after_dispatch',
    'orders.shortage.resolve',
    'orders.assign_agent',
    'deliveries.manage',
    'drivers.manage',
    'returns.inspect',
    'returns.approve',
    'returns.refund',
    'reviews.moderate',
    'retrieval.view',
    'retrieval.open',
    'retrieval.receive',
    'reports.view',
    'loyalty.adjust',
  ],
  catalog_editor: [
    'catalog.categories',
    'catalog.brands',
    'catalog.products',
    'prices.change',
    'prices.publish_linked',
    'sell_below_cost.approve',
    'cost.view',
    'fx_rates.view',
  ],
  stock_controller: [
    'cost.view',
    'suppliers.view',
    'suppliers.manage',
    'purchases.create',
    'purchases.correct',
    'purchases.override_rate',
    'supplier_openings.record',
    'supplier_credits.allocate',
    'supplier_returns.create',
    'inventory.count',
    'inventory.pick',
    'inventory.adjust',
    'inventory.transfer',
    'inventory.view',
    'inventory.manage',
    'inventory.write_down',
    'fx_rates.view',
  ],
  cashier: [
    'suppliers.view',
    'supplier_payments.record',
    'supplier_payments.reverse',
    'cash_accounts.view',
    'fx_rates.view',
  ],
  accountant: [
    'suppliers.view',
    'supplier_payments.record',
    'supplier_payments.reverse',
    'cash_accounts.view',
    'cash_accounts.manage',
    'fx_rates.view',
    'fx_rates.update',
    'ledger.view',
    'ledger.reverse',
    'period.close',
    'period.reopen',
    'backdate.approve',
    'reports.view',
  ],
} as const satisfies Record<string, readonly PermissionKey[]>;
