import 'package:flutter/material.dart';
import '../../../../core/l10n/generated/app_localizations.dart';

class CategoryIconEntry {
  const CategoryIconEntry(this.key, this.icon, this.group, this.keywords);
  final String key, group, keywords;
  final IconData icon;
  String label(AppLocalizations l) => CategoryIconCatalog.label(key, l);
}

/// Stable semantic keys; only this presentation registry knows Material glyphs.
abstract final class CategoryIconCatalog {
  static const fallback = Icons.category;
  static const entries = <CategoryIconEntry>[
    CategoryIconEntry(
      'electronics_devices',
      Icons.devices,
      'electronics',
      'Devices أجهزة electronic tablet تابلت',
    ),
    CategoryIconEntry(
      'electronics_cable',
      Icons.cable,
      'electronics',
      'Cables كابلات charging شحن',
    ),
    CategoryIconEntry(
      'electronics_router',
      Icons.router,
      'electronics',
      'Routers موجهات wifi internet انترنت',
    ),
    CategoryIconEntry(
      'electronics_tv',
      Icons.tv,
      'electronics',
      'Televisions تلفزيونات screen شاشة',
    ),
    CategoryIconEntry(
      'electronics_power',
      Icons.electrical_services,
      'electronics',
      'Electrical supplies كهربائيات plug socket قابس',
    ),
    CategoryIconEntry(
      'electronics_battery',
      Icons.battery_full,
      'electronics',
      'Batteries بطاريات power طاقة',
    ),
    CategoryIconEntry(
      'mobile_phone',
      Icons.smartphone,
      'phones',
      'Phones هواتف mobile جوال موبايل',
    ),
    CategoryIconEntry(
      'mobile_tablet',
      Icons.tablet_mac,
      'phones',
      'Tablets أجهزة لوحية ipad تابلت',
    ),
    CategoryIconEntry(
      'mobile_charging',
      Icons.charging_station,
      'phones',
      'Chargers شواحن power شحن',
    ),
    CategoryIconEntry(
      'mobile_watch',
      Icons.watch,
      'phones',
      'Smart watches ساعات ذكية wearable ارتداء',
    ),
    CategoryIconEntry(
      'computer_laptop',
      Icons.laptop,
      'computers',
      'Laptops حواسيب محمولة notebook لابتوب',
    ),
    CategoryIconEntry(
      'computer_desktop',
      Icons.desktop_windows,
      'computers',
      'Desktop computers حواسيب مكتبية pc كمبيوتر',
    ),
    CategoryIconEntry(
      'computer_keyboard',
      Icons.keyboard,
      'computers',
      'Keyboards لوحات مفاتيح typing كتابة',
    ),
    CategoryIconEntry(
      'computer_mouse',
      Icons.mouse,
      'computers',
      'Mice فأرات computer حاسوب',
    ),
    CategoryIconEntry(
      'computer_printer',
      Icons.print,
      'computers',
      'Printers طابعات ink حبر',
    ),
    CategoryIconEntry(
      'computer_storage',
      Icons.sd_storage,
      'computers',
      'Storage وحدات تخزين memory ذاكرة',
    ),
    CategoryIconEntry(
      'audio_headphones',
      Icons.headphones,
      'audio',
      'Headphones سماعات رأس music موسيقى',
    ),
    CategoryIconEntry(
      'audio_earbuds',
      Icons.earbuds,
      'audio',
      'Earbuds سماعات أذن wireless لاسلكي',
    ),
    CategoryIconEntry(
      'audio_speaker',
      Icons.speaker,
      'audio',
      'Speakers مكبرات صوت sound صوت',
    ),
    CategoryIconEntry(
      'audio_mic',
      Icons.mic,
      'audio',
      'Microphones ميكروفونات recording تسجيل',
    ),
    CategoryIconEntry(
      'audio_radio',
      Icons.radio,
      'audio',
      'Radios راديو broadcast إذاعة',
    ),
    CategoryIconEntry(
      'camera_photo',
      Icons.photo_camera,
      'cameras',
      'Cameras كاميرات photography تصوير',
    ),
    CategoryIconEntry(
      'camera_video',
      Icons.videocam,
      'cameras',
      'Video cameras كاميرات فيديو film أفلام',
    ),
    CategoryIconEntry(
      'camera_lens',
      Icons.camera,
      'cameras',
      'Lenses عدسات photography تصوير',
    ),
    CategoryIconEntry(
      'camera_security',
      Icons.linked_camera,
      'cameras',
      'Security cameras كاميرات مراقبة cctv مراقبة',
    ),
    CategoryIconEntry(
      'gaming_console',
      Icons.sports_esports,
      'gaming',
      'Game consoles أجهزة ألعاب playstation بلايستيشن',
    ),
    CategoryIconEntry(
      'gaming_controller',
      Icons.gamepad,
      'gaming',
      'Controllers أذرع تحكم games ألعاب',
    ),
    CategoryIconEntry(
      'fashion_clothing',
      Icons.checkroom,
      'fashion',
      'Clothing ملابس fashion أزياء',
    ),
    CategoryIconEntry(
      'fashion_men',
      Icons.man,
      'fashion',
      'Menswear ملابس رجالية men رجال',
    ),
    CategoryIconEntry(
      'fashion_women',
      Icons.woman,
      'fashion',
      'Womenswear ملابس نسائية women نساء',
    ),
    CategoryIconEntry(
      'fashion_shoes',
      Icons.hiking,
      'fashion',
      'Footwear أحذية boots shoes حذاء',
    ),
    CategoryIconEntry(
      'fashion_uniform',
      Icons.engineering,
      'fashion',
      'Workwear ملابس عمل uniform زي',
    ),
    CategoryIconEntry(
      'fashion_laundry',
      Icons.local_laundry_service,
      'fashion',
      'Clothing care عناية بالملابس fabric قماش',
    ),
    CategoryIconEntry(
      'accessories_watch',
      Icons.watch,
      'accessories',
      'Watches ساعات time ساعة',
    ),
    CategoryIconEntry(
      'accessories_bag',
      Icons.work,
      'accessories',
      'Bags حقائب handbag حقيبة',
    ),
    CategoryIconEntry(
      'accessories_backpack',
      Icons.backpack,
      'accessories',
      'Backpacks حقائب ظهر school مدرسة',
    ),
    CategoryIconEntry(
      'accessories_luggage',
      Icons.luggage,
      'accessories',
      'Luggage حقائب سفر travel سفر',
    ),
    CategoryIconEntry(
      'accessories_jewelry',
      Icons.diamond,
      'accessories',
      'Jewelry مجوهرات gold ذهب',
    ),
    CategoryIconEntry(
      'accessories_umbrella',
      Icons.umbrella,
      'accessories',
      'Umbrellas مظلات rain مطر',
    ),
    CategoryIconEntry(
      'home_furniture',
      Icons.weekend,
      'home',
      'Furniture أثاث sofa couch أريكة',
    ),
    CategoryIconEntry(
      'home_chair',
      Icons.chair,
      'home',
      'Chairs كراسي seat مقعد',
    ),
    CategoryIconEntry('home_bed', Icons.bed, 'home', 'Beds أسرّة sleep نوم'),
    CategoryIconEntry(
      'home_table',
      Icons.table_restaurant,
      'home',
      'Tables طاولات dining مائدة',
    ),
    CategoryIconEntry(
      'home_lighting',
      Icons.lightbulb,
      'home',
      'Lighting إضاءة lamp مصباح',
    ),
    CategoryIconEntry(
      'home_bath',
      Icons.bathtub,
      'home',
      'Bathroom حمام bath استحمام',
    ),
    CategoryIconEntry(
      'home_curtains',
      Icons.curtains,
      'home',
      'Curtains ستائر window نافذة',
    ),
    CategoryIconEntry(
      'home_bedding',
      Icons.bedroom_parent,
      'home',
      'Bedding مفروشات pillow وسادة',
    ),
    CategoryIconEntry(
      'kitchen_appliances',
      Icons.kitchen,
      'kitchen',
      'Appliances أجهزة مطبخ fridge ثلاجة',
    ),
    CategoryIconEntry(
      'kitchen_cooking',
      Icons.restaurant,
      'kitchen',
      'Cookware أواني طبخ pot قدر',
    ),
    CategoryIconEntry(
      'kitchen_tableware',
      Icons.local_cafe,
      'kitchen',
      'Tableware أدوات مائدة cup كوب',
    ),
    CategoryIconEntry(
      'kitchen_blender',
      Icons.blender,
      'kitchen',
      'Blenders خلاطات juice عصير',
    ),
    CategoryIconEntry(
      'kitchen_microwave',
      Icons.microwave,
      'kitchen',
      'Microwaves مايكروويف oven فرن',
    ),
    CategoryIconEntry(
      'kitchen_kettle',
      Icons.coffee_maker,
      'kitchen',
      'Coffee makers ماكينات قهوة espresso اسبريسو',
    ),
    CategoryIconEntry(
      'cleaning_supplies',
      Icons.cleaning_services,
      'cleaning',
      'Cleaning supplies أدوات تنظيف broom مكنسة',
    ),
    CategoryIconEntry(
      'cleaning_soap',
      Icons.soap,
      'cleaning',
      'Soap صابون wash غسل',
    ),
    CategoryIconEntry(
      'cleaning_bins',
      Icons.recycling,
      'cleaning',
      'Waste bins سلال نفايات trash سلة',
    ),
    CategoryIconEntry(
      'cleaning_water',
      Icons.water_drop,
      'cleaning',
      'Water care معالجة المياه filter فلتر',
    ),
    CategoryIconEntry(
      'grocery_food',
      Icons.shopping_basket,
      'food',
      'Groceries بقالة food تموين',
    ),
    CategoryIconEntry(
      'food_rice',
      Icons.rice_bowl,
      'food',
      'Rice & grains أرز وحبوب staples رز',
    ),
    CategoryIconEntry(
      'food_bakery',
      Icons.bakery_dining,
      'food',
      'Bakery مخبوزات bread خبز',
    ),
    CategoryIconEntry(
      'food_fruit',
      Icons.apple,
      'food',
      'Fruit فواكه apple تفاح',
    ),
    CategoryIconEntry(
      'food_vegetables',
      Icons.eco,
      'food',
      'Vegetables خضروات fresh طازج',
    ),
    CategoryIconEntry(
      'food_meat',
      Icons.kebab_dining,
      'food',
      'Meat لحوم beef لحم',
    ),
    CategoryIconEntry(
      'food_seafood',
      Icons.set_meal,
      'food',
      'Seafood أسماك fish سمك',
    ),
    CategoryIconEntry(
      'food_pizza',
      Icons.local_pizza,
      'food',
      'Pizza بيتزا frozen مجمد',
    ),
    CategoryIconEntry(
      'food_icecream',
      Icons.icecream,
      'food',
      'Ice cream مثلجات dessert حلويات',
    ),
    CategoryIconEntry('food_cake', Icons.cake, 'food', 'Cakes كيك sweets حلوى'),
    CategoryIconEntry(
      'food_eggs',
      Icons.egg,
      'food',
      'Eggs بيض breakfast فطور',
    ),
    CategoryIconEntry(
      'food_snacks',
      Icons.cookie,
      'food',
      'Snacks وجبات خفيفة biscuit بسكويت',
    ),
    CategoryIconEntry(
      'drinks_coffee',
      Icons.coffee,
      'drinks',
      'Coffee قهوة beans بن',
    ),
    CategoryIconEntry(
      'drinks_tea',
      Icons.emoji_food_beverage,
      'drinks',
      'Tea شاي herbal أعشاب',
    ),
    CategoryIconEntry(
      'drinks_juice',
      Icons.local_drink,
      'drinks',
      'Juices عصائر drink مشروب',
    ),
    CategoryIconEntry(
      'drinks_water',
      Icons.water,
      'drinks',
      'Water مياه bottled ماء',
    ),
    CategoryIconEntry(
      'beauty_spa',
      Icons.spa,
      'beauty',
      'Beauty care عناية وجمال wellness تجميل',
    ),
    CategoryIconEntry(
      'beauty_skin',
      Icons.face,
      'beauty',
      'Skin care عناية بالبشرة cream كريم',
    ),
    CategoryIconEntry(
      'beauty_hair',
      Icons.content_cut,
      'beauty',
      'Hair care عناية بالشعر shampoo شامبو',
    ),
    CategoryIconEntry(
      'beauty_cosmetics',
      Icons.brush,
      'beauty',
      'Cosmetics مستحضرات تجميل makeup مكياج',
    ),
    CategoryIconEntry(
      'beauty_health',
      Icons.health_and_safety,
      'beauty',
      'Health supplies مستلزمات صحية care صحة',
    ),
    CategoryIconEntry(
      'beauty_hygiene',
      Icons.clean_hands,
      'beauty',
      'Personal hygiene نظافة شخصية hygiene عناية',
    ),
    CategoryIconEntry(
      'beauty_medical',
      Icons.medical_services,
      'beauty',
      'First aid إسعافات أولية bandage ضماد',
    ),
    CategoryIconEntry(
      'sport_fitness',
      Icons.fitness_center,
      'sport',
      'Fitness لياقة weights أثقال',
    ),
    CategoryIconEntry(
      'sport_cycling',
      Icons.pedal_bike,
      'sport',
      'Cycling دراجات bicycle دراجة',
    ),
    CategoryIconEntry(
      'sport_football',
      Icons.sports_soccer,
      'sport',
      'Football كرة قدم ball كرة',
    ),
    CategoryIconEntry(
      'sport_basketball',
      Icons.sports_basketball,
      'sport',
      'Basketball كرة سلة ball كرة',
    ),
    CategoryIconEntry(
      'sport_tennis',
      Icons.sports_tennis,
      'sport',
      'Tennis تنس racket مضرب',
    ),
    CategoryIconEntry(
      'sport_swimming',
      Icons.pool,
      'sport',
      'Swimming سباحة swim مسبح',
    ),
    CategoryIconEntry(
      'sport_camping',
      Icons.festival,
      'sport',
      'Camping تخييم tent خيمة',
    ),
    CategoryIconEntry(
      'sport_fishing',
      Icons.phishing,
      'sport',
      'Fishing صيد أسماك rod صنارة',
    ),
    CategoryIconEntry(
      'kids_baby',
      Icons.child_care,
      'kids',
      'Baby care عناية بالطفل infant رضيع',
    ),
    CategoryIconEntry(
      'kids_stroller',
      Icons.stroller,
      'kids',
      'Strollers عربات أطفال baby طفل',
    ),
    CategoryIconEntry(
      'kids_toys',
      Icons.toys,
      'kids',
      'Toys ألعاب أطفال play لعب',
    ),
    CategoryIconEntry(
      'kids_puzzle',
      Icons.extension,
      'kids',
      'Puzzles ألعاب تركيب puzzle أحجية',
    ),
    CategoryIconEntry(
      'kids_scooter',
      Icons.skateboarding,
      'kids',
      'Skates & scooters تزلج وسكوتر skate لوح',
    ),
    CategoryIconEntry(
      'auto_car',
      Icons.directions_car,
      'auto',
      'Car supplies مستلزمات سيارات car سيارة',
    ),
    CategoryIconEntry(
      'auto_motorcycle',
      Icons.two_wheeler,
      'auto',
      'Motorcycles دراجات نارية motor دراجة',
    ),
    CategoryIconEntry(
      'auto_tires',
      Icons.tire_repair,
      'auto',
      'Tires إطارات wheel عجلات',
    ),
    CategoryIconEntry(
      'auto_fuel',
      Icons.local_gas_station,
      'auto',
      'Fuel & oils وقود وزيوت oil زيت',
    ),
    CategoryIconEntry(
      'auto_tools',
      Icons.car_repair,
      'auto',
      'Car tools أدوات سيارات repair صيانة',
    ),
    CategoryIconEntry(
      'books_reading',
      Icons.menu_book,
      'books',
      'Books كتب reading قراءة',
    ),
    CategoryIconEntry(
      'books_notebooks',
      Icons.auto_stories,
      'books',
      'Notebooks دفاتر paper ورق',
    ),
    CategoryIconEntry(
      'books_pens',
      Icons.draw,
      'books',
      'Pens أقلام writing كتابة',
    ),
    CategoryIconEntry(
      'books_art',
      Icons.palette,
      'books',
      'Art supplies لوازم فنية paint رسم',
    ),
    CategoryIconEntry(
      'books_school',
      Icons.school,
      'books',
      'School supplies لوازم مدرسية education تعليم',
    ),
    CategoryIconEntry(
      'pets_supplies',
      Icons.pets,
      'garden',
      'Pet supplies مستلزمات حيوانات cat dog قط كلب',
    ),
    CategoryIconEntry(
      'garden_trees',
      Icons.park,
      'garden',
      'Garden plants نباتات حدائق tree شجرة',
    ),
    CategoryIconEntry(
      'garden_flowers',
      Icons.local_florist,
      'garden',
      'Flowers زهور plant نبات',
    ),
    CategoryIconEntry(
      'garden_tools',
      Icons.hardware,
      'garden',
      'Hand tools أدوات يدوية hammer مطرقة',
    ),
    CategoryIconEntry(
      'garden_building',
      Icons.construction,
      'garden',
      'Building supplies مواد بناء tools معدات',
    ),
    CategoryIconEntry(
      'garden_solar',
      Icons.solar_power,
      'garden',
      'Solar supplies طاقة شمسية panel لوح',
    ),
    CategoryIconEntry(
      'garden_watering',
      Icons.yard,
      'garden',
      'Garden care عناية بالحديقة watering ري',
    ),
    CategoryIconEntry(
      'gifts_present',
      Icons.redeem,
      'gifts',
      'Gifts هدايا present هدية',
    ),
    CategoryIconEntry(
      'beauty_fragrance',
      Icons.sanitizer,
      'beauty',
      'Fragrances عطور perfume scent عطر',
    ),
    CategoryIconEntry(
      'gifts_party',
      Icons.celebration,
      'gifts',
      'Party supplies لوازم حفلات party حفل',
    ),
    CategoryIconEntry(
      'general_crafts',
      Icons.handyman,
      'gifts',
      'Craft supplies أشغال يدوية craft حرف',
    ),
    CategoryIconEntry(
      'general_music',
      Icons.piano,
      'gifts',
      'Musical instruments آلات موسيقية music موسيقى',
    ),
    CategoryIconEntry(
      'general_category',
      Icons.category,
      'gifts',
      'General products منتجات عامة general عام',
    ),
  ];
  static final byKey = {for (final entry in entries) entry.key: entry};
  static IconData resolve(String? key) => byKey[key]?.icon ?? fallback;
  static String normalize(String value) => value
      .toLowerCase()
      .replaceAll(RegExp('[أإآ]'), 'ا')
      .replaceAll(RegExp('[ًٌٍَُِّْـ]'), '');
  static List<CategoryIconEntry> search(String query, {String? group}) {
    final words = normalize(query).trim().split(RegExp(r'\s+'));
    return entries
        .where(
          (entry) =>
              (group == null || entry.group == group) &&
              words.every(
                (word) =>
                    normalize('${entry.key} ${entry.keywords}').contains(word),
              ),
        )
        .toList();
  }

  static String label(String key, AppLocalizations l) => switch (key) {
    'electronics_devices' => l.categoryIconElectronicsDevices,
    'electronics_cable' => l.categoryIconElectronicsCable,
    'electronics_router' => l.categoryIconElectronicsRouter,
    'electronics_tv' => l.categoryIconElectronicsTv,
    'electronics_power' => l.categoryIconElectronicsPower,
    'electronics_battery' => l.categoryIconElectronicsBattery,
    'mobile_phone' => l.categoryIconMobilePhone,
    'mobile_tablet' => l.categoryIconMobileTablet,
    'mobile_charging' => l.categoryIconMobileCharging,
    'mobile_watch' => l.categoryIconMobileWatch,
    'computer_laptop' => l.categoryIconComputerLaptop,
    'computer_desktop' => l.categoryIconComputerDesktop,
    'computer_keyboard' => l.categoryIconComputerKeyboard,
    'computer_mouse' => l.categoryIconComputerMouse,
    'computer_printer' => l.categoryIconComputerPrinter,
    'computer_storage' => l.categoryIconComputerStorage,
    'audio_headphones' => l.categoryIconAudioHeadphones,
    'audio_earbuds' => l.categoryIconAudioEarbuds,
    'audio_speaker' => l.categoryIconAudioSpeaker,
    'audio_mic' => l.categoryIconAudioMic,
    'audio_radio' => l.categoryIconAudioRadio,
    'camera_photo' => l.categoryIconCameraPhoto,
    'camera_video' => l.categoryIconCameraVideo,
    'camera_lens' => l.categoryIconCameraLens,
    'camera_security' => l.categoryIconCameraSecurity,
    'gaming_console' => l.categoryIconGamingConsole,
    'gaming_controller' => l.categoryIconGamingController,
    'fashion_clothing' => l.categoryIconFashionClothing,
    'fashion_men' => l.categoryIconFashionMen,
    'fashion_women' => l.categoryIconFashionWomen,
    'fashion_shoes' => l.categoryIconFashionShoes,
    'fashion_uniform' => l.categoryIconFashionUniform,
    'fashion_laundry' => l.categoryIconFashionLaundry,
    'accessories_watch' => l.categoryIconAccessoriesWatch,
    'accessories_bag' => l.categoryIconAccessoriesBag,
    'accessories_backpack' => l.categoryIconAccessoriesBackpack,
    'accessories_luggage' => l.categoryIconAccessoriesLuggage,
    'accessories_jewelry' => l.categoryIconAccessoriesJewelry,
    'accessories_umbrella' => l.categoryIconAccessoriesUmbrella,
    'home_furniture' => l.categoryIconHomeFurniture,
    'home_chair' => l.categoryIconHomeChair,
    'home_bed' => l.categoryIconHomeBed,
    'home_table' => l.categoryIconHomeTable,
    'home_lighting' => l.categoryIconHomeLighting,
    'home_bath' => l.categoryIconHomeBath,
    'home_curtains' => l.categoryIconHomeCurtains,
    'home_bedding' => l.categoryIconHomeBedding,
    'kitchen_appliances' => l.categoryIconKitchenAppliances,
    'kitchen_cooking' => l.categoryIconKitchenCooking,
    'kitchen_tableware' => l.categoryIconKitchenTableware,
    'kitchen_blender' => l.categoryIconKitchenBlender,
    'kitchen_microwave' => l.categoryIconKitchenMicrowave,
    'kitchen_kettle' => l.categoryIconKitchenKettle,
    'cleaning_supplies' => l.categoryIconCleaningSupplies,
    'cleaning_soap' => l.categoryIconCleaningSoap,
    'cleaning_bins' => l.categoryIconCleaningBins,
    'cleaning_water' => l.categoryIconCleaningWater,
    'grocery_food' => l.categoryIconGroceryFood,
    'food_rice' => l.categoryIconFoodRice,
    'food_bakery' => l.categoryIconFoodBakery,
    'food_fruit' => l.categoryIconFoodFruit,
    'food_vegetables' => l.categoryIconFoodVegetables,
    'food_meat' => l.categoryIconFoodMeat,
    'food_seafood' => l.categoryIconFoodSeafood,
    'food_pizza' => l.categoryIconFoodPizza,
    'food_icecream' => l.categoryIconFoodIcecream,
    'food_cake' => l.categoryIconFoodCake,
    'food_eggs' => l.categoryIconFoodEggs,
    'food_snacks' => l.categoryIconFoodSnacks,
    'drinks_coffee' => l.categoryIconDrinksCoffee,
    'drinks_tea' => l.categoryIconDrinksTea,
    'drinks_juice' => l.categoryIconDrinksJuice,
    'drinks_water' => l.categoryIconDrinksWater,
    'beauty_spa' => l.categoryIconBeautySpa,
    'beauty_skin' => l.categoryIconBeautySkin,
    'beauty_hair' => l.categoryIconBeautyHair,
    'beauty_cosmetics' => l.categoryIconBeautyCosmetics,
    'beauty_health' => l.categoryIconBeautyHealth,
    'beauty_hygiene' => l.categoryIconBeautyHygiene,
    'beauty_medical' => l.categoryIconBeautyMedical,
    'sport_fitness' => l.categoryIconSportFitness,
    'sport_cycling' => l.categoryIconSportCycling,
    'sport_football' => l.categoryIconSportFootball,
    'sport_basketball' => l.categoryIconSportBasketball,
    'sport_tennis' => l.categoryIconSportTennis,
    'sport_swimming' => l.categoryIconSportSwimming,
    'sport_camping' => l.categoryIconSportCamping,
    'sport_fishing' => l.categoryIconSportFishing,
    'kids_baby' => l.categoryIconKidsBaby,
    'kids_stroller' => l.categoryIconKidsStroller,
    'kids_toys' => l.categoryIconKidsToys,
    'kids_puzzle' => l.categoryIconKidsPuzzle,
    'kids_scooter' => l.categoryIconKidsScooter,
    'auto_car' => l.categoryIconAutoCar,
    'auto_motorcycle' => l.categoryIconAutoMotorcycle,
    'auto_tires' => l.categoryIconAutoTires,
    'auto_fuel' => l.categoryIconAutoFuel,
    'auto_tools' => l.categoryIconAutoTools,
    'books_reading' => l.categoryIconBooksReading,
    'books_notebooks' => l.categoryIconBooksNotebooks,
    'books_pens' => l.categoryIconBooksPens,
    'books_art' => l.categoryIconBooksArt,
    'books_school' => l.categoryIconBooksSchool,
    'pets_supplies' => l.categoryIconPetsSupplies,
    'garden_trees' => l.categoryIconGardenTrees,
    'garden_flowers' => l.categoryIconGardenFlowers,
    'garden_tools' => l.categoryIconGardenTools,
    'garden_building' => l.categoryIconGardenBuilding,
    'garden_solar' => l.categoryIconGardenSolar,
    'garden_watering' => l.categoryIconGardenWatering,
    'gifts_present' => l.categoryIconGiftsPresent,
    'beauty_fragrance' => l.categoryIconBeautyFragrance,
    'gifts_party' => l.categoryIconGiftsParty,
    'general_crafts' => l.categoryIconGeneralCrafts,
    'general_music' => l.categoryIconGeneralMusic,
    'general_category' => l.categoryIconGeneralCategory,
    _ => l.categoryIconGeneralCategory,
  };
  static String groupLabel(String group, AppLocalizations l) => switch (group) {
    'electronics' => l.categoryGroupElectronics,
    'phones' => l.categoryGroupPhones,
    'computers' => l.categoryGroupComputers,
    'audio' => l.categoryGroupAudio,
    'cameras' => l.categoryGroupCameras,
    'gaming' => l.categoryGroupGaming,
    'fashion' => l.categoryGroupFashion,
    'accessories' => l.categoryGroupAccessories,
    'home' => l.categoryGroupHome,
    'kitchen' => l.categoryGroupKitchen,
    'cleaning' => l.categoryGroupCleaning,
    'food' => l.categoryGroupFood,
    'drinks' => l.categoryGroupDrinks,
    'beauty' => l.categoryGroupBeauty,
    'sport' => l.categoryGroupSport,
    'kids' => l.categoryGroupKids,
    'auto' => l.categoryGroupAuto,
    'books' => l.categoryGroupBooks,
    'garden' => l.categoryGroupGarden,
    'gifts' => l.categoryGroupGifts,
    _ => l.categoryAllGroups,
  };
}
