import '../../../../core/l10n/generated/app_localizations.dart';
import '../../domain/admin_repository.dart';

String adminTitle(AppLocalizations l, AdminResource r) => switch (r) {
  AdminResource.products => l.adminProducts,
  AdminResource.categories => l.adminCategories,
  AdminResource.users => l.adminSectionUsers,
  AdminResource.roles => l.adminRoles,
  AdminResource.suppliers => l.adminSuppliers,
  AdminResource.warehouses => l.adminWarehouses,
  AdminResource.locations => l.adminLocations,
  AdminResource.permissions => l.adminPermissions,
};
String adminFieldLabel(AppLocalizations l, String field) => switch (field) {
  'name' => l.adminFieldName,
  'name_ar' => l.adminFieldNameAr,
  'name_en' => l.adminFieldNameEn,
  'phone' => l.adminFieldPhone,
  'email' => l.adminFieldEmail,
  'address' => l.adminFieldAddress,
  'description' => l.adminFieldDescription,
  'sale_price' => l.adminFieldPrice,
  'compare_at_price' => l.adminOriginalPrice,
  'floor_price' => l.adminFieldFloorPrice,
  'points_price' => l.adminFieldPointsPrice,
  'icon' => l.adminFieldIcon,
  'sort_order' => l.adminFieldSort,
  'is_active' => l.adminFieldActive,
  'password' => l.adminFieldPassword,
  'parent_id' => l.adminFieldParent,
  'category_id' => l.adminFieldCategory,
  'role' => l.adminFieldRole,
  'status' => l.adminFieldStatus,
  'tracks_expiry' => l.adminFieldExpiry,
  'is_negotiable' => l.adminFieldNegotiable,
  'images' => l.adminImages,
  'variants' => l.adminVariants,
  'permissions' => l.adminPermissions,
  'zone' => l.adminZone,
  'aisle' => l.adminAisle,
  'shelf' => l.adminShelf,
  'bin' => l.adminBin,
  _ => field,
};
String adminStatusLabel(AppLocalizations l, String status) => switch (status) {
  'active' => l.adminStatusActive,
  'hidden' => l.adminStatusHidden,
  'archived' => l.adminStatusArchived,
  _ => status,
};

String adminPermissionLabel(AppLocalizations l, String key) => switch (key) {
  'catalog.view' => l.adminPermissionCatalogView,
  'catalog.manage' => l.adminPermissionCatalogManage,
  'orders.view' => l.adminPermissionOrdersView,
  'orders.confirm' => l.adminPermissionOrdersConfirm,
  'orders.update' => l.adminPermissionOrdersUpdate,
  'inventory.view' => l.adminPermissionInventoryView,
  'inventory.pick' => l.adminPermissionInventoryPick,
  'inventory.adjust' => l.adminPermissionInventoryAdjust,
  'inventory.transfer' => l.adminPermissionInventoryTransfer,
  'purchasing.view' => l.adminPermissionPurchasingView,
  'purchasing.manage' => l.adminPermissionPurchasingManage,
  'returns.view' => l.adminPermissionReturnsView,
  'returns.process' => l.adminPermissionReturnsProcess,
  'delivery.assigned' => l.adminPermissionDeliveryAssigned,
  'loyalty.manage' => l.adminPermissionLoyaltyManage,
  'users.manage' => l.adminPermissionUsersManage,
  'reports.view' => l.adminPermissionReportsView,
  'settings.manage' => l.adminPermissionSettingsManage,
  _ => key,
};
